/*
@TargetNode='Localhost'
*/

instance of MSFT_nxPackageResource
{
                Name = "*";
                ResourceId = "[MSFT_nxPackageResource]Inventory";
                ModuleName = "PSDesiredStateConfiguration";
                ModuleVersion = "1.0";


};

instance of MSFT_nxServiceResource
{
                Name = "*";
                Controller = "*";
                ResourceId = "[MSFT_nxServiceResource]Inventory";
                ModuleName = "PSDesiredStateConfiguration";
                ModuleVersion = "1.0";


};


instance of OMI_ConfigurationDocument
{
  DocumentType = "inventory";

     Version="2.0.0";
     MinimumCompatibleVersion = "2.0.0";
     Name="InventoryConfig";


};


