/*
@TargetNode='Localhost'
*/

instance of MSFT_nxAvailableUpdatesResource
{
    Name = "*";
    ResourceId = "[MSFT_nxAvailableUpdates]Inventory";
    ModuleName = "nx";
    ModuleVersion = "1.0";
};


instance of OMI_ConfigurationDocument
{
    DocumentType = "inventory";

    Version="2.0.0";
    MinimumCompatibleVersion = "2.0.0";
    Name="InventoryConfig";
};
