#!/bin/bash

# check if running as root
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root in order to install the troubleshooter, due to the permissions required for the destination directories."
    echo "Please instead run:"
    echo ""
    echo "$ sudo ./install_tsg"
    echo ""
    echo "in order to install the troubleshooter."
    exit 1
fi

BIN_PATH="/opt/microsoft/omsagent/bin/"
OMSAGENT_TSG_PATH="${BIN_PATH}/omsagent_tsg"
PLUGIN_TSG_PATH="/opt/microsoft/omsagent/plugin/troubleshooter"

echo "Getting ready to install troubleshooter..."

# set up machine

if [ -d $PLUGIN_TSG_PATH ]; then
    # get rid of old files to update
    echo "Removing older version of troubleshooter..."
    rm -rf $PLUGIN_TSG_PATH
    rm -f $OMSAGENT_TSG_PATH
fi

# copy over files
echo "Installing troubleshooter on machine..."
mkdir -p $PLUGIN_TSG_PATH
cp -r tsg_files/tsg_code $PLUGIN_TSG_PATH
cp -r tsg_files/tsg_tools $PLUGIN_TSG_PATH
cp tsg_files/omsagent_tsg $BIN_PATH

echo "You can now run the troubleshooter by going to $BIN_PATH and running the below command:"
echo ""
echo "$ sudo ./omsagent_tsg"
echo ""