#! /bin/bash

#
# Helper functions for omsagent service control
#
# This script can be "sourced" (if sourcing with the "functions" qualifer),
# which is used by the service control scripts. This allows for deeper control
# of the process at a low level.
#
# Otherwise (this is the normal case), invoke this with one of the following
# options:
#
#    start:    Start the OMS service via the service control manager
#    stop:     Stop the OMS service via the service control manager
#    restart:  Restart the OMS service via the service control manager
#    reload:   Reload agent configuration
#

VAR_DIR=/var/opt/microsoft/omsagent
ETC_DIR=/etc/opt/microsoft/omsagent
BIN_DIR=/opt/microsoft/omsagent/bin

WORKSPACE_REGEX='^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'

setup_variables()
{
    if [ -z "$1" ]; then
        if [ -f $ETC_DIR/conf/omsadmin.conf ]; then
            . "$ETC_DIR/conf/omsadmin.conf"
        else
            echo "Warning: No workspace is onboarded"
            exit 0 
        fi
    else
        if [ -f $ETC_DIR/$1/conf/omsadmin.conf ]; then
            . "$ETC_DIR/$1/conf/omsadmin.conf"
        else
            echo "Warning: Specified workspace $1 does not exist on the machine. Check the correctness of the workspace ID and that onboarding succeeded."
            exit 0
        fi
    fi

    VAR_DIR_WS=$VAR_DIR/$WORKSPACE_ID
    ETC_DIR_WS=$ETC_DIR/$WORKSPACE_ID

    TMP_DIR=$VAR_DIR_WS/tmp
    STATE_DIR=$VAR_DIR_WS/state
    RUN_DIR=$VAR_DIR_WS/run
    LOG_DIR=$VAR_DIR_WS/log
    CERT_DIR=$ETC_DIR_WS/certs
    CONF_DIR=$ETC_DIR_WS/conf

    LOGFILE=$LOG_DIR/omsagent.log
    PIDFILE=$RUN_DIR/omsagent.pid
    CONFFILE=$CONF_DIR/omsagent.conf
    OMSADMIN_CONF=$CONF_DIR/omsadmin.conf

    OMSAGENT_WS=omsagent-$WORKSPACE_ID
}

verify_privileges()
{
    if [ `id -u` -ne 0 ]; then
        echo "Must have root privileges for this operation" >& 2
        exit 1
    fi
}

is_omsagent_running()
{
    verify_privileges

    # Returns 1 if 'omsagent' is running, 0 otherwise
    [ -f $PIDFILE ] || return 0
    ps -p `cat $PIDFILE` | grep -q omsagent
    STATUS=$?

    # Kill PID file if we're not running any longer
    if [ $STATUS -ne 0 ]; then
        rm -f $PIDFILE
        return 0
    else
        return 1
    fi
}

exit_if_agent_not_onboarded()
{
    if [ ! -f $OMSADMIN_CONF ]; then
        echo "Warning: Agent is not onboarded. omsagent cannot be registered as a service."
        exit 0 
    fi
}

wait_until_omsagent_stops()
{
    # Required parameter: Number of seconds to wait for agent to stop
    if [ -z "$1" -o "$1" -le 0 ]; then
        echo "Function \"wait_until_omsagent_stops\" called with invalid parameter"
        exit 1
    fi

    COUNTER=$(( $1 * 2 )) # Since we sleep 0.5 seconds, compute number of seconds
    while [ $COUNTER -gt 0 ]; do
        is_omsagent_running && return $?
        COUNTER=$(( $COUNTER - 1 ))
        sleep 0.5
    done

    # One final try for accurate return status (just return status from the call)
    is_omsagent_running
}

stop_omsagent_process()
{
    # First try sending a graceful shutdown request.
    # If omsagent doesn't stop, forcefully kill it.
    #
    # TODO: omsagent doesn't currently gracefully shut down, we're investigating this later

    is_omsagent_running && return $?

    # kill -sigterm `cat $PIDFILE`
    # wait_until_omsagent_stops 10 && return $?

    echo -n "(Forced) "
    kill -sigkill `cat $PIDFILE`
    wait_until_omsagent_stops 5
    return $?
}

start_omsagent_process()
{
    is_omsagent_running && /opt/microsoft/omsagent/bin/omsagent -d $PIDFILE --no-supervisor -o $LOGFILE -c $CONFFILE
}

#
# Normal usage functions (used by everything except service control scripts)
#

start_omsagent()
{
    exit_if_agent_not_onboarded
    enable_omsagent_service
    is_omsagent_running
    [ $? -ne 0 ] && return

    # If systemd lives here, then we have a systemd unit file
    if pidof systemd 1> /dev/null 2> /dev/null; then
        /bin/systemctl start $OMSAGENT_WS
    else
        if [ -x /usr/sbin/invoke-rc.d ]; then
            /usr/sbin/invoke-rc.d $OMSAGENT_WS start
        elif [ -x /sbin/service ]; then
            /sbin/service $OMSAGENT_WS start
        elif [ -x /bin/systemctl ]; then
            /bin/systemctl start $OMSAGENT_WS
        else
            echo "Unrecognized service controller to start OMS Agent service" 1>&2
            exit 1
        fi
    fi
}

stop_omsagent()
{
    is_omsagent_running
    if [ $? -ne 0 ]; then
        # If systemd lives here, then we have a systemd unit file
        if pidof systemd 1> /dev/null 2> /dev/null; then
            /bin/systemctl stop $OMSAGENT_WS
        else
            if [ -x /usr/sbin/invoke-rc.d ]; then
                /usr/sbin/invoke-rc.d $OMSAGENT_WS stop
            elif [ -x /sbin/service ]; then
                /sbin/service $OMSAGENT_WS stop
            elif [ -x /bin/systemctl ]; then
                /bin/systemctl stop $OMSAGENT_WS
            else
                echo "Unrecognized service controller to stop OMS Agent service" 1>&2
                exit 1
            fi
        fi
    fi
}

restart_omsagent()
{
    exit_if_agent_not_onboarded
    
    is_omsagent_running
    if [ $? -eq 0 ]; then
        start_omsagent
        return
    else
        enable_omsagent_service
    fi

    # If systemd lives here, then we have a systemd unit file
    if pidof systemd 1> /dev/null 2> /dev/null; then
        /bin/systemctl restart $OMSAGENT_WS
    else
        if [ -x /usr/sbin/invoke-rc.d ]; then
            /usr/sbin/invoke-rc.d $OMSAGENT_WS restart
        elif [ -x /sbin/service ]; then
            /sbin/service $OMSAGENT_WS restart
        elif [ -x /bin/systemctl ]; then
            /bin/systemctl restart $OMSAGENT_WS
        else
            echo "Unrecognized service controller to restart OMS Agent service" 1>&2
            exit 1
        fi
    fi
}


find_systemd_dir()
{
    # Various distributions have different paths for systemd unit files ...
    local UNIT_DIR_LIST="/usr/lib/systemd/system /lib/systemd/system"

    if pidof systemd 1> /dev/null 2> /dev/null; then
        # Be sure systemctl lives where we expect it to
        if [ ! -f /bin/systemctl ]; then
            echo "FATAL: Unable to locate systemctl program" 1>&2
            exit 1
        fi

        # Find systemd unit directory
        for i in ${UNIT_DIR_LIST}; do
            if [ -d $i ]; then
                echo ${i}
                return 0
            fi
        done

        # Didn't find unit directory, that's fatal
        echo "FATAL: Unable to resolve systemd unit directory!" 1>&2
        exit 1
    else
        return 1
    fi
}

enable_omsagent_service()
{
    exit_if_agent_not_onboarded
    if [ ! -f $CONF_DIR/.service_registered ] && [ -f $OMSADMIN_CONF ]; then
        echo "Configuring OMS agent service ..."
        if [ ! -f $BIN_DIR/$OMSAGENT_WS ]; then
            ln -s $BIN_DIR/omsagent $BIN_DIR/$OMSAGENT_WS
        fi

        if pidof systemd 1> /dev/null 2> /dev/null; then
            # systemd
            local systemd_dir=$(find_systemd_dir)
            local omsagent_service=${systemd_dir}/$OMSAGENT_WS.service

            cp /etc/opt/microsoft/omsagent/sysconf/omsagent.systemd $omsagent_service 

            sed -i s,%CONF_DIR_WS%,$CONF_DIR,1 $omsagent_service
            sed -i s,%CERT_DIR_WS%,$CERT_DIR,1 $omsagent_service
            sed -i s,%TMP_DIR_WS%,$TMP_DIR,1 $omsagent_service
            sed -i s,%RUN_DIR_WS%,$RUN_DIR,1 $omsagent_service
            sed -i s,%STATE_DIR_WS%,$STATE_DIR,1 $omsagent_service
            sed -i s,%LOG_DIR_WS%,$LOG_DIR,1 $omsagent_service

            /bin/systemctl daemon-reload
            /bin/systemctl -q enable $OMSAGENT_WS
        else
            local omsagent_initd=/etc/init.d/$OMSAGENT_WS
            cp /etc/opt/microsoft/omsagent/sysconf/omsagent.ulinux $omsagent_initd

            sed -i s,%WORKSPACE_ID%,$WORKSPACE_ID,g $omsagent_initd

            if [ -x /usr/sbin/update-rc.d ]; then
                update-rc.d $OMSAGENT_WS defaults > /dev/null
            elif [ -x /usr/lib/lsb/install_initd ]; then
                /usr/lib/lsb/install_initd $omsagent_initd
            elif [ -x /sbin/chkconfig ]; then
                /sbin/chkconfig --add $OMSAGENT_WS > /dev/null
            else
                echo "Could not find a service controller to configure the OMS Agent Service."
                exit 1
            fi
        fi
        touch  $CONF_DIR/.service_registered
    fi 
}


disable_omsagent_service()
{
    # Stop the server if it's running
    stop_omsagent

    # Registered as a systemd service?
    local systemd_dir=$(find_systemd_dir)
    local omsagent_service=${systemd_dir}/$OMSAGENT_WS.service
    local omsagent_initd=/etc/init.d/$OMSAGENT_WS
    if [ -f $omsagent_service ]; then
        echo "Unconfiguring OMS agent (systemd) service ..."
        /bin/systemctl -q disable $OMSAGENT_WS
        rm -f $omsagent_service
        /bin/systemctl daemon-reload
    elif [ -f $omsagent_initd ]; then
        echo "Unconfiguring OMS agent service ..."
        if [ -f /usr/sbin/update-rc.d ]; then
            /usr/sbin/update-rc.d -f $OMSAGENT_WS remove
        elif [ -x /usr/lib/lsb/remove_initd ]; then
            /usr/lib/lsb/remove_initd $omsagent_initd
        elif [ -x /sbin/chkconfig ]; then
            /sbin/chkconfig --del $OMSAGENT_WS > /dev/null
        else
            echo "Unrecognized Service Controller to unregister OMS Agent Service."
            exit 1
        fi

        rm $omsagent_initd
    fi
    rm -f $CONF_DIR/.service_registered
}

start_all_omsagent()
{
    for ws_id in `ls -1 $ETC_DIR | grep -E $WORKSPACE_REGEX`
    do
       setup_variables ${ws_id}
       start_omsagent
    done
}

stop_all_omsagent()
{
    for ws_id in `ls -1 $ETC_DIR | grep -E $WORKSPACE_REGEX`
    do
       setup_variables ${ws_id}
       stop_omsagent
    done
}

restart_all_omsagent()
{
    for ws_id in `ls -1 $ETC_DIR | grep -E $WORKSPACE_REGEX`
    do
       setup_variables ${ws_id}
       restart_omsagent
    done
}

enable_all_omsagent_services()
{
    for ws_id in `ls -1 $ETC_DIR | grep -E $WORKSPACE_REGEX`
    do
       setup_variables ${ws_id}
       enable_omsagent_service
    done
}

disable_all_omsagent_services()
{
    for ws_id in `ls -1 $ETC_DIR | grep -E $WORKSPACE_REGEX`
    do
       setup_variables ${ws_id}
       disable_omsagent_service
    done
}

case "$1" in
    functions)
        setup_variables $2
        ;;

    is-running)
        setup_variables $2
        is_omsagent_running
        exit $?
        ;;

    start)
        if [ -z $2 ]; then
            start_all_omsagent
        else
            setup_variables $2
            start_omsagent
        fi
        ;;

    stop)
        if [ -z $2 ]; then
            stop_all_omsagent
        else
            setup_variables $2
            stop_omsagent
        fi
        ;;

    restart)
        if [ -z $2 ]; then
            restart_all_omsagent
        else
            setup_variables $2
            restart_omsagent
        fi
        ;;

    reload)
        # TODO: Due to a bug in OMS right now, we can't reload via a signal
        if [ -z $2 ]; then
            restart_all_omsagent
        else
            setup_variables $2
            restart_omsagent
        fi
        ;;

    find-systemd-dir)
        find_systemd_dir
        ;;

    enable)
        if [ -z $2 ]; then
            enable_all_omsagent_services
        else
            setup_variables $2
            enable_omsagent_service
        fi
        ;;

    disable)
        if [ -z $2 ]; then
	    disable_all_omsagent_services
        else
            setup_variables $2
	    disable_omsagent_service
        fi
        ;;

    *)
        echo "Unknown parameter : $1" 1>&2
        exit 1
        ;;
esac
